default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: shorten_urls_development

test:
  <<: *default
  database: shorten_urls_test

production:
  <<: *default
  database: shorten_urls_production

# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: torn_trader_development

# test:
#   <<: *default
#   database: torn_trader_test


# production:
#   <<: *default
#   username: <%= ENV['DB_USERNAME'] %>
#   password: <%= ENV['DB_PASSWORD'] %>
#   database: torntrader_production
#   host: <%= ENV['DB_HOST'] %>
#   port: 5432