default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: urls
  username: admin
  password: 

test:
  <<: *default
  database: urls
  username: admin
  password:

production:
  <<: *default
  database: urls


